name: Release Publish

on:
  workflow_run:
    workflows: ["Release Testing"]
    types:
      - completed
    branches:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only run if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Get version from tag
      id: get_version
      run: |
        TAG="${{ github.event.workflow_run.head_branch }}"
        VERSION="${TAG#v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Update version in pyproject.toml
      run: |
        poetry version ${{ steps.get_version.outputs.version }}

    - name: Build package
      run: poetry build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        files: dist/*
        generate_release_notes: true
        draft: false

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
      # TODO: Remove this condition when PyPI is set up
      if: false

  notify-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
    - name: Create issue for failed release
      uses: actions/github-script@v7
      with:
        script: |
          const tag = context.payload.workflow_run.head_branch;
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Release ${tag} failed tests`,
            body: `The release tests for tag ${tag} failed. Please check the [workflow run](${context.payload.workflow_run.html_url}) for details.`,
            labels: ['bug', 'release']
          });
